### ISSUE TITLE
Support different Lagoons

### ISSUE THREAD

**Issue by bomoko** [uselagoon/lagoon-sync#34]
Currently lagoon-sync has the IO lagoon hardcoded - we need to make this configurable

https://github.com/uselagoon/lagoon-sync/blob/5790b4dd6bbf89df84c3f828f1f044340480c10a/synchers/syncdefs.go#L83

**Comment by timclifford** [comment]
https://github.com/uselagoon/lagoon-sync/pull/38/files

**Comment by tobybellwood** [comment]
ok - having a tthink about this.

We already have a defined method for providing a ssh host in a .lagoon.yml https://docs.lagoon.sh/using-lagoon-the-basics/lagoon-yml/#ssh - we should use this instead of having to double add the ssh details.

In addition, we should be able to utilise an already defined ssh if it exists in the ~/.lagoon.yml - if it is defined for lagoon-cli use.

Perhaps if lagoon-sync is called with the `-l` flag (as per lagoon-cli) - it can read the ~/.lagoon.yml file and parse out the ssh host and port?

**Comment by bomoko** [comment]
Closed via #38
